local parser = require('erde.parser.string')

spec('valid short string', function()
  assert.are.equal('"hello"', parser.unit('"hello"'))
  assert.are.equal("'hello'", parser.unit("'hello'"))
  assert.are.equal("'hello\\nworld'", parser.unit("'hello\\nworld'"))
  assert.are.equal("'\\\\'", parser.unit("'\\\\'"))
end)

spec('invalid short string', function()
  assert.has_error(function()
    parser.unit('hello"')
  end)
  assert.has_error(function()
    parser.unit('"hello')
  end)
  assert.has_error(function()
    parser.unit('"hello\nworld"')
  end)
  assert.has_error(function()
    parser.unit("hello'")
  end)
  assert.has_error(function()
    parser.unit("'hello")
  end)
  assert.has_error(function()
    parser.unit("'hello\nworld'")
  end)
end)
