local unit = require('erde.parser.unit')

spec('valid short string', function()
  assert.are.equal('"hello"', unit.string('"hello"'))
  assert.are.equal("'hello'", unit.string("'hello'"))
  assert.are.equal("'hello\\nworld'", unit.string("'hello\\nworld'"))
  assert.are.equal("'\\\\'", unit.string("'\\\\'"))
end)

spec('invalid short string', function()
  assert.has_error(function()
    unit.string('hello"')
  end)
  assert.has_error(function()
    unit.string('"hello')
  end)
  assert.has_error(function()
    unit.string('"hello\nworld"')
  end)
  assert.has_error(function()
    unit.string("hello'")
  end)
  assert.has_error(function()
    unit.string("'hello")
  end)
  assert.has_error(function()
    unit.string("'hello\nworld'")
  end)
end)
