-- Most tests in tokenizer_spec. Here we just test for valid tokens that are
-- invalid as numbers
spec('Number.parse', function()
  assert.has_error(function()
    parse.Number('x3')
  end)
  assert.has_error(function()
    parse.Number('e2')
  end)
  assert.has_error(function()
    parse.Number('.e2')
  end)
  assert.has_error(function()
    parse.Number('.1ef')
  end)
end)
