local lexer = require('erde.lexer.number')

spec('valid integer', function()
  assert.are.equal('9', lexer.unit('9'))
  assert.are.equal('43', lexer.unit('43'))
end)

spec('invalid integer', function()
  assert.has_error(function()
    lexer.unit('')
  end)
end)

spec('valid hex', function()
  assert.are.equal('0x4', lexer.unit('0x4'))
  assert.are.equal('0xd', lexer.unit('0xd'))
  assert.are.equal('0Xf', lexer.unit('0Xf'))
  assert.are.equal('0xa8F', lexer.unit('0xa8F'))
end)

spec('invalid hex', function()
  assert.has_error(function()
    lexer.unit('x3')
  end)
  assert.has_error(function()
    lexer.unit('0x')
  end)
  assert.has_error(function()
    lexer.unit('0xg')
  end)
  assert.has_error(function()
    lexer.unit('4xg')
  end)
end)

spec('valid integer exponent', function()
  assert.are.equal('9e2', lexer.unit('9e2'))
  assert.are.equal('9E21', lexer.unit('9E21'))
  assert.are.equal('9e+2', lexer.unit('9e+2'))
  assert.are.equal('9e-2', lexer.unit('9e-2'))
end)

spec('invalid integer exponent', function()
  assert.has_error(function()
    lexer.unit('9e')
  end)
  assert.has_error(function()
    lexer.unit('9e+')
  end)
  assert.has_error(function()
    lexer.unit('9e-')
  end)
  assert.has_error(function()
    lexer.unit('e2')
  end)
end)

spec('valid float', function()
  assert.are.equal('.34', lexer.unit('.34'))
  assert.are.equal('0.3', lexer.unit('0.3'))
  assert.are.equal('10.33', lexer.unit('10.33'))
end)

spec('invalid float', function()
  assert.has_error(function()
    lexer.unit('4.')
  end)
end)

spec('valid float exponent', function()
  assert.are.equal('9.2e2', lexer.unit('9.2e2'))
  assert.are.equal('9.01E21', lexer.unit('9.01E21'))
  assert.are.equal('0.1e+2', lexer.unit('0.1e+2'))
  assert.are.equal('.8e-2', lexer.unit('.8e-2'))
end)

spec('invalid float exponent', function()
  assert.has_error(function()
    lexer.unit('9.1e')
  end)
  assert.has_error(function()
    lexer.unit('9.1e+')
  end)
  assert.has_error(function()
    lexer.unit('9.1e-')
  end)
end)
