local lexer = require('erde.lexer.string')

spec('valid short string', function()
  assert.are.equal('"hello"', lexer.unit('"hello"'))
  assert.are.equal("'hello'", lexer.unit("'hello'"))
  assert.are.equal("'hello\\nworld'", lexer.unit("'hello\\nworld'"))
  assert.are.equal("'\\\\'", lexer.unit("'\\\\'"))
end)

spec('invalid short string', function()
  assert.has_error(function()
    lexer.unit('hello"')
  end)
  assert.has_error(function()
    lexer.unit('"hello')
  end)
  assert.has_error(function()
    lexer.unit('"hello\nworld"')
  end)
  assert.has_error(function()
    lexer.unit("hello'")
  end)
  assert.has_error(function()
    lexer.unit("'hello")
  end)
  assert.has_error(function()
    lexer.unit("'hello\nworld'")
  end)
end)
