local inspect = require('inspect')
local ls = require('init')

describe('syntax::number', function()
  test('Hex', function()
    assert.same('0xff', ls.compile(ls.parse('0xff')))
    assert.same('0xBEBADA', ls.compile(ls.parse('0xBEBADA')))
    assert.same('0X4', ls.compile(ls.parse('0X4')))
    assert.same('0X0F03', ls.compile(ls.parse('0X0F03')))
  end)

  test('Exponent', function()
    assert.same('0x4', ls.compile(ls.parse('0x4')))
    assert.same('0x4D2', ls.compile(ls.parse('0x4D2')))
    assert.same('0X4', ls.compile(ls.parse('0X4')))
    assert.same('0X0F03', ls.compile(ls.parse('0X0F03')))
  end)
end)
